imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true
    bind:
      $module: '@oksydan.is_shoppingcart.module'
      $context: '@oksydan.is_shoppingcart.context'

  Oksydan\IsShoppingcart\:
    resource: '../../src/*'
    exclude:
      - '../../src/{Controller,Form}'
      - '../../src/index.php'
      - '../../src/*/index.php'

  Oksydan\IsShoppingcart\Hook\:
    resource: '../../src/Hook/*'
    public: true
    exclude:
      - '../../src/Hook/index.php'
      - '../../src/Hook/*/index.php'

  Oksydan\IsShoppingcart\View\:
    resource: '../../src/View/*'
    public: true
    exclude:
      - '../../src/View/index.php'
      - '../../src/View/*/index.php'

  Oksydan\IsShoppingcart\Configuration\ShoppingCartConfiguration:
    class: Oksydan\IsShoppingcart\Configuration\ShoppingCartConfiguration
    public: true

  Oksydan\IsShoppingcart\Persister\TemplateVarsPersister:
    class: Oksydan\IsShoppingcart\Persister\TemplateVarsPersister
    public: true
