imports:
  - { resource: ../common.yml }


services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true
    bind:
      $module: '@oksydan.is_shoppingcart.module'
      $context: '@oksydan.is_shoppingcart.context'

  Oksydan\IsShoppingcart\:
    resource: '../../src/*'
    exclude:
      - '../../src/{Controller,Form}'
      - '../../src/index.php'
      - '../../src/*/index.php'
