imports:
  - { resource: ../common.yml }

services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true
    bind:
      $module: '@oksydan.is_shoppingcart.module'
      $context: '@oksydan.is_shoppingcart.context'
      $shopContext: '@prestashop.adapter.shop.context'
      $multistoreFeature: '@prestashop.adapter.multistore_feature'
      $locales: '@=service("prestashop.adapter.legacy.context").getLanguages()'

  Oksydan\IsShoppingcart\:
    resource: '../../src/*'
    exclude:
      - '../../src/{Controller}'
      - '../../src/index.php'
      - '../../src/*/index.php'

  oksydan.is_shoppingcart.configuration.form_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@Oksydan\IsShoppingcart\Form\Provider\ShoppingCartConfigurationFormDataProvider'
      - 'Oksydan\IsShoppingcart\Form\Type\ShoppingCartConfigurationType'
      - 'ConfigurationForm'
