services:
  _defaults:
    public: true

  oksydan.is_shoppingcart.module:
    class: Is_shoppingcart
    factory: [ 'Module', 'getInstanceByName' ]
    public: false
    arguments:
      - 'is_shoppingcart'

  oksydan.is_shoppingcart.context:
    class: Context
    factory: [ '\Context', getContext ]
